#!/bin/bash

# ----------------------------------------------------------------------------------------
# GENERAL INFORMATION
# ----------------------------------------------------------------------------------------
#
# Written by Andrew J Freyer
# GNU General Public License
# http://github.com/andrewjfreyer/monitor
#
# PACKET INFORMATION GATHERING
#
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# EXTRACT GENERAL ACCESS PROFILE NAME FROM ADV PACKET
# ----------------------------------------------------------------------------------------
gap_name () {
	#SET PACKET FROM INPUT
	local packet="$1"

	#LOCAL STRING
	local name_as_string=""

	#IS A GAP NAME GIVE? COMPLETE OR LOCAL? 
	local gap_name=$(echo "$packet" | awk '{print $16}')

	#CHECK IF GAP DATA IS 
	if [[ $gap_name =~ ^0[89] ]]; then
		#HEX CONVERSION
		local name_len_hex=$(echo "$packet" | awk '{print $15}')

		#DECIMAL CONVERSION
		local name_len_dec=$(echo "ibase=16; $name_len_hex" | bc)
		
		#STR CHARACTER COUNT (2 CHAR + 1 _SPACE_ PER BYTE)
		local name_len_str=$(((name_len_dec - 1) * 3))
		
		#EXTRACT LOCAL NAME
		local name_as_string=$(echo "${packet:48:name_len_str}" | xxd -r -p)

		#CLEANUP
		name_as_string=$(echo "$name_as_string" | sed 's/[^0-9a-zA-Z]//g;s/  */ /g;s/ $//g;s/^ //g')

		log "NAME: $name_as_string"
	fi

	#RETURN NAME
    echo "$name_as_string"
}

# ----------------------------------------------------------------------------------------
# OBTAIN PROTOCOL DATA UNIT TYPE
# ----------------------------------------------------------------------------------------

pdu_type () {
	#IF NO ADDRESS, RETURN BLANK
	local pdu_type_str="Reserved"
	
	if [ ! -z "$1" ]; then  
		local pdu_type="$1"
		case $pdu_type in
			"00"|0 )
				pdu_type_str="ADV_IND"
				;;
			"01"|1)
				pdu_type_str="ADV_DIRECT_IND"
				;;	
			"02"|2)
				pdu_type_str="ADV_NONCONN_IND"
				;;	
			"03"|3)
				#THIS SHOULD BE 'SCAN_REQ' PER THE BLUETOOTH SPEC; 
				#BUT HCIDUMP APPEARS TO REPORT THIS AS AN ADV
				#THIS AS ADV_NON
				pdu_type_str="ADV_NONCONN_IND"
				;;	
			"04"|4)
				pdu_type_str="SCAN_RSP"
				;;	
			"05"|5)
				pdu_type_str="CONNECT_REQ"
				;;	
			"06"|6)
				pdu_type_str="ADV_SCAN_IND"
				;;	
			*)
				pdu_type_str="Reserved"
				;;	
		esac
	fi 

	#RETURN
	echo "$pdu_type_str"
}


# ----------------------------------------------------------------------------------------
# OBTAIN MANUFACTURER INFORMATION FOR A PARTICULAR BLUETOOTH MAC ADDRESS
# ----------------------------------------------------------------------------------------
determine_manufacturer () {

	#IF NO ADDRESS, RETURN BLANK
	if [ ! -z "$1" ]; then  
		local address="$1"

		#SET THE FILE IF IT DOESN'T EXIST
		[ ! -f ".manufacturer_cache" ] && echo "" > ".manufacturer_cache"

		#CHECK CACHE
		local manufacturer=$(grep "${address:0:8}" < ".manufacturer_cache" | awk -F "\t" '{print $2}')

		#IF CACHE DOES NOT EXIST, USE MACVENDORS.COM
		if [ -z "$manufacturer" ]; then 
			local remote_result=$(curl -sL https://api.macvendors.com/${address:0:8} | grep -vi "error")

			#MAKE SURE WE DONT' SCREW UP THE MANUFACTUERE'S FILE
			if [[ ! $remote_result =~ *"html"* ]]; then
				[ ! -z "$remote_result" ] && echo "${address:0:8}	$remote_result" >> .manufacturer_cache
				manufacturer="$remote_result"
			fi 
		fi

		#SET DEFAULT MANUFACTURER 
		[ -z "$manufacturer" ] && manufacturer="Unknown"
		echo "$manufacturer"
	fi 
}