#!/bin/bash

# ----------------------------------------------------------------------------------------
# GENERAL INFORMATION
# ----------------------------------------------------------------------------------------
#
# Written by Andrew J Freyer
# GNU General Public License
# http://github.com/andrewjfreyer/monitor
#
# PRINTING AND DEBUGGING
#
# ----------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------
# PRETTY PRINT FOR DEBUG
# ----------------------------------------------------------------------------------------

#COLOR OUTPUT FOR RICH OUTPUT 
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
REPEAT='\e[1A'

#VARIABLES FOR LOGGING LOGSPAM PREVENTION
last_log_line=""
duplicate_log_count=1

#FORK THE LOG FROM THE MAIN THREAD 
log_listener () {
	#LOG PIPE
	while true; do 
		#READ FROM THE MAIN PIPE
		while read line; do 

			#ECHO TO CONSOLE, REMOVING EXTRA SPACES	
			should_repeat=""
			line_append=""

			#IS THIS LINE DUPLICATED?
			if [ "$last_log_line" == "$line" ] ; then 
				duplicate_log_count=$((duplicate_log_count + 1 ))
				line_append=" (x$duplicate_log_count)"
				should_repeat=$REPEAT

			else 
				duplicate_log_count=1
			fi   
			#ECHO LAST LINE
			bash echo -e "${should_repeat}$version $(date "+%I:%M:%S %p") $line$line_append"
			last_log_line="$line"

		done < log_pipe

		#PREVENT INFINITE LOOPING
		sleep 1
	done 
}


#PRINT TO LOG UNLESS DUPLICATE LINE
log() {
	#SEND TO LOG PIPE
	echo "$1" | sed 's/  */ /g' > log_pipe
}