#!/bin/bash

# ----------------------------------------------------------------------------------------
# GENERAL INFORMATION
# ----------------------------------------------------------------------------------------
#
# Written by Andrew J Freyer
# GNU General Public License
# http://github.com/andrewjfreyer/monitor
#
# HELP FILE AND GENERAL PREFERENCES
#
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# HELP TEXT
# ----------------------------------------------------------------------------------------

show_help_text() {
	echo "Usage:"
	echo "  monitor -h 		show usage information"
	echo "  monitor -v		print version number"
	echo "  monitor -p		periodically scan for arrival & departure of known devices"
	echo "  monitor -b		scan for & report BTLE beacon advertisements"
	echo "  monitor -a		report all scan results, not just presence changes"
	echo "  monitor -P		scan for & report public address advertisements"
	echo "  monitor -t		scan only on mqtt trigger messages:"
	echo "				$mqtt_topicpath/scan/ARRIVE"
	echo "				$mqtt_topicpath/scan/DEPART"
}

# ----------------------------------------------------------------------------------------
# PROCESS OPTIONS (technique: https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash)
# ----------------------------------------------------------------------------------------

OPTIND=1

#PREFERENCES
PREF_PERIODIC_MODE=false
PREF_BEACON_MODE=false
PREF_TRIGGER_MODE=false
PREF_PUBLIC_MODE=false
PREF_REPORT_ALL_MODE=false

while getopts "h?vpbtPa:" opt; do
    case "$opt" in
    h|\?)
        show_help_text
        exit 0
        ;;
    v)  
		echo "$VERSION"
		exit 0
		;;
    p)  PREF_PERIODIC_MODE=true && echo "> periodic scan mode enabled"
		;;
    b)  PREF_BEACON_MODE=true && echo "> beacon scan mode enabled"
		;;
    P)  PREF_PUBLIC_MODE=true && echo "> public node scan mode enabled"
		;;
	t)  PREF_TRIGGER_MODE=true && echo "> trigger only mode enabled"
		;;
	a)  PREF_REPORT_ALL_MODE=true && echo "> report all scan results mode enabled"
		;;
    esac
done

#RESET OPTION INDEX
shift $((OPTIND-1))

#SHIFT IF NECESSARY
[ "$1" = "--" ] && shift