#!/bin/bash

# ----------------------------------------------------------------------------------------
# GENERAL INFORMATION
# ----------------------------------------------------------------------------------------
#
# Written by Andrew J Freyer
# GNU General Public License
# http://github.com/andrewjfreyer/monitor
#
# TIME BASED TRIGGERS
#
# ----------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------
# PERIODIC TRIGGER TO MAIN LOOP
# ----------------------------------------------------------------------------------------
periodic_trigger (){
	while : ; do 
		sleep "$PREF_CLOCK_INTERVAL"
		echo "TIME" > main_pipe
	done
}

# ----------------------------------------------------------------------------------------
# PERIODIC TRIGGER TO MAIN LOOP
# ----------------------------------------------------------------------------------------
refresh_databases (){
	while : ; do 
		sleep "$PREF_DATABASE_REFRESH_INTERVAL"
		echo "REFR" > main_pipe
	done
}